[tools]
bat = "latest"
fzf = "latest"
gh = "latest"
ghq = "latest"
jq = "latest"
node = "latest"
python = "3.13"
starship = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
helix = "latest"
eza = "latest"
yazi = "latest"
codex = "latest"
claude = "latest"
"npm:bash-language-server" = "latest"
