[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'cespare/vim-toml'

[[plugins]]
repo = 'plasticboy/vim-markdown'

[[plugins]]
repo = 'nixprime/cpsm'

[[plugins]]
repo = 'kana/vim-operator-user'

[[plugins]]
repo = 'tomasr/molokai'
